name: "legacy_checks"
repository: "https://github.com/lishaduck/legacy_checks.git"

packages:
  - packages/**

command:
  bootstrap:
    enforceLockfile: true
    fetchTags: false

    environment:
      sdk: "^3.5.0"

  version:
    changelogFormat:
      includeDate: true
    branch: main
    hooks:
      preCommit: melos run get && git add packages/*/pubspec.lock

scripts:
  get:
    description: get dependencies (no lockfile update, linking)
    exec: dart pub get
  upgrade:
    description: upgrade dependencies
    exec: dart pub upgrade
  custom_lint:
    description: run custom lint
    exec: dart run custom_lint --fatal-infos
    packageFilters:
      dependsOn:
        - custom_lint
  test:
    description: run tests
    exec: dart run very_good_cli:very_good test --coverage --test-randomize-ordering-seed random
    packageFilters:
      dependsOn:
        - very_good_cli
