name: "legacy_checks"
repository: "https://github.com/lishaduck/legacy_checks"

packages:
  - packages/**

command:
  bootstrap:
    enforceLockfile: true
    fetchTags: false

    environment:
      sdk: "^3.6.0"

  version:
    changelogFormat:
      includeDate: true
    branch: main
    hooks:
      preCommit: dart pub get && git add packages/*/pubspec.lock

scripts:
  custom_lint:
    description: run custom lint
    exec: dart run custom_lint --fatal-infos
    packageFilters:
      dependsOn:
        - custom_lint
  test:
    description: run tests
    exec: dart run very_good_cli:very_good test --coverage --test-randomize-ordering-seed random
    packageFilters:
      dependsOn:
        - very_good_cli
