name: legacy_checks_workspace
repository: https://github.com/lishaduck/legacy_checks

publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: "3.35.4"

workspace:
  - packages/_analysis_options
  - packages/flutter_checks
  - packages/legacy_checks

dev_dependencies:
  melos: ^7.0.0-dev.8

melos:
  command:
    bootstrap:
      environment:
        sdk: "^3.7.0"

    version:
      changelogFormat:
        includeDate: true
      branch: main

  scripts:
    test:
      description: run tests
      exec: dart run very_good_cli:very_good test --coverage --test-randomize-ordering-seed random
      packageFilters:
        dependsOn:
          - very_good_cli
    pana:
      description: run pana
      exec: dart run pana . --exit-code-threshold=130
      packageFilters:
        noPrivate: true
