name: _

publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: "3.27.1"

workspace:
  - packages/analysis_options
  - packages/flutter_checks
  - packages/legacy_checks

dev_dependencies:
  melos: ^6.2.0
