name: analysis_options
description: "Analyzer configuration for the legacy_checks monorepo."
version: 0.0.1
homepage: https://lishaduck.github.io
documentation: https://github.com/lishaduck/legacy_checks
issue_tracker: https://github.com/lishaduck/legacy_checks/issues
repository: https://github.com/lishaduck/legacy_checks.git

publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  very_good_analysis: ^7.0.0

dev_dependencies:
  custom_lint: ^0.7.0
