name: flutter_checks
description: "Add typesafe support for legacy matchers from `package:flutter_test` to `package:checks` expectations."
version: 0.1.2
homepage: https://github.com/lishaduck/legacy_checks
documentation: https://github.com/lishaduck/legacy_checks
issue_tracker: https://github.com/lishaduck/legacy_checks/issues
repository: https://github.com/lishaduck/legacy_checks.git

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"
resolution: workspace

topics:
  - "testing"

dependencies:
  checks: ^0.3.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  legacy_checks: ^0.1.1
  matcher: ^0.12.16+1
  vector_math: ^2.1.4

dev_dependencies:
  _analysis_options: ^0.0.0
  very_good_cli: ^0.27.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
