# Dispatched by `tag.yaml`
---
name: Publish

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CI: true

permissions: {}

jobs:
  publish:
    name: Publish
    timeout-minutes: 10
    runs-on: ubuntu-latest

    permissions:
      id-token: write
    environment: publish

    steps:
      - name: 📚 Git checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive
          clean: true
          persist-credentials: false
          set-safe-directory: true
      - name: 🐦 Set up Flutter
        id: flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          flutter-version-file: pubspec.yaml
          cache: true
      - name: 🌐 Disable analytics
        run: flutter --disable-analytics
      - name: 📦 Install dependencies
        uses: bluefireteam/melos-action@2982f8e4fc92440a219490009d6d05195cb1a6a5 # v3.8.0
        with:
          melos-version: 7.0.0-dev.8
          dart-version: none
          enforce-lockfile: true
          publish: true
